import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { WebSocketProvider } from "./context/websocket.contex";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata: Metadata = {
  title: "FPT student campus",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Global error handler for uncaught JavaScript errors
              window.addEventListener('error', function(e) {
                if (e.message && e.message.includes('timer is not defined')) {
                  console.warn('VNPay timer error caught and ignored:', e.message);
                  e.preventDefault();
                  return false;
                }
              });
            `,
          }}
        />
      </head>
      <body className={`${roboto.variable} font-sans antialiased`}>
        <WebSocketProvider>{children}</WebSocketProvider>
      </body>
    </html>
  );
}
